[#e4,reftext=E.4]
=== (E.4) Assumptions

ifdef::env-draft[]
TIP: _Properties of the environment that may be assumed, with the goal of facilitating the project and simplifying the system. It defines properties that are not imposed by the environment (like those in <<e3>>) but assumed to hold, as an explicit decision meant to facilitate the system's construction._  <<BM22>>
endif::[]


*	*User is understanding of how to download/install basic windows programs.*:	As we cannot be there to install this program on every computer it will run on, we assume that the user is able to install it by themselves provided they are provided an installer program file. 

*	*User understands basic computer I/O (Keyboard, mouse, screen).*: To properly intact with the program users would be expected to know how to use their keyboard and mouse to navigate the program. This would include keyboard shortcuts. 

*	*User not needlessly interact with Files in the system.*: The Program will store taken note files on the computer.it is assumed that the user will not do changes to files that may cause issues when reading the files. 

*	*Device being run on has proper libraries or user can install them when provided with redists.*: If our program uses other libraries, they need to install for it to work. If the user can install the program than it is assumed that the user can also install required libraires. These libraries need to be provided either as a list or as redistributable files. 

*	*The device running the program has enough space for the program to function.*: The program will require drive space to store the program and any notes created by the user. If there is not enough space the user should be notified, and the program should continue to hold the current note.
