name: Build and Push AsciiDoctor Docs

on:
  push:
    branches:
      # - main
      - "**"
    paths:
      - '**/*.adoc'
      - 'docs/**'
  pull_request:
    branches:
      # - main
      - "**"
    paths:
      - '**/*.adoc'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Asciidoctor tools
        run: |
          gem install asciidoctor asciidoctor-pdf asciidoctor-diagram
          sudo apt-get update
          sudo apt-get install -y graphviz default-jre  # for PlantUML
          sudo wget -O /usr/local/bin/plantuml https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
          echo '#!/bin/sh' | sudo tee /usr/local/bin/plantuml.sh
          echo 'java -jar /usr/local/bin/plantuml "$@"' | sudo tee -a /usr/local/bin/plantuml.sh
          sudo chmod +x /usr/local/bin/plantuml.sh

      - name: Build docs using Makefile
        run: |
          cd docs/SRS-Meyer
          make

      - name: Commit and push generated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-build docs from Asciidoctor"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

